### ISSUE TITLE
Confusing error for the pacakge python3-ldb-devel

### ISSUE THREAD

**Issue by lslebodn** [fedora-python/task-python-versions#6]
```
These RPMs require both Python 2 and Python 3:
python3-ldb-devel-1.1.29-1.fc25.armv7hl.rpm
python3-ldb-devel-1.1.29-1.fc25.i686.rpm
python3-ldb-devel-1.1.29-1.fc25.x86_64.rpm

Read the following document to find more information and a possible cause:
https://python-rpm-porting.readthedocs.io/en/latest/applications.html#are-shebangs-dragging-you-down-to-python-2
Or ask at #fedora-python IRC channel for help

If you think the result is false or intentional, file a bug against:
https://github.com/fedora-python/task-python-versions/issues
```
python3-ldb-devel requires just a python3 and 
https://koji.fedoraproject.org/koji/rpminfo?rpmID=9585716

**Comment by hroncok** [comment]
It requires `python-ldb-devel-common` and that one is considered to be Python 2. And since it's not true, I'll add it to the whitelist.

**Comment by lslebodn** [comment]
Ahh , the assumption is based on the beginning of name "python-...". 
I think we could also rename package. You know python packaging guidelines better. Feel free to open BZ.

But the main point of this ticket is to improve error reporting. Because it was not clear from the output what is wrong.

**Comment by hroncok** [comment]
There's a extended log that says why this happened. Was it not accessible?

**Comment by hroncok** [comment]
> I think we could also rename package. You know python packaging guidelines better. Feel free to open BZ.

Actually we are trying to rename all Python 2 packages to python2-, so the name here is fine. We are treating python- here as Python 2 for historical reasons and hopefully will be able to drop that assumption soon.

**Comment by lslebodn** [comment]
> There's a extended log that says why this happened. Was it not accessible?

I am not sure what do you mean

https://bodhi.fedoraproject.org/updates/FEDORA-2017-61c75669ea
 -> Automated Tests
        -> dist.python-versions

Did I miss something?

**Comment by hroncok** [comment]
Well, you did not. Apparently the link to the log is not there in bodhi.

If you click the check and remove the `output.log`, you'll ghet here:

https://taskotron.fedoraproject.org/artifacts/all/fa300624-2f1a-11e7-a212-5254008e42f6/task_output/

And you can see:

https://taskotron.fedoraproject.org/artifacts/all/fa300624-2f1a-11e7-a212-5254008e42f6/task_output/taskotron.log.gz

Honestly, I don't know why the full log is not accessible.

What if the message looked like this:

```
These RPMs require both Python 2 and Python 3:
python3-ldb-devel-1.1.29-1.fc25.armv7hl.rpm
 * Python 2 dependency: python-ldb-devel-common(armv7hl-32)
 * Python 3 dependecny: python3-ldb(armv7hl-32)
python3-ldb-devel-1.1.29-1.fc25.i686.rpm
 * Python 2 dependency: python-ldb-devel-common(x86-32)
 * Python 3 dependecny: python3-ldb(x86-32)
python3-ldb-devel-1.1.29-1.fc25.x86_64.rpm
 * Python 2 dependency: python-ldb-devel-common(x86-64)
 * Python 3 dependecny: python3-ldb(x86-64)

Read the following document to find more information and a possible cause:
https://python-rpm-porting.readthedocs.io/en/latest/applications.html#are-shebangs-dragging-you-down-to-python-2
Or ask at #fedora-python IRC channel for help.

If you think the result is false or intentional, file a bug against:
https://github.com/fedora-python/task-python-versions/issues
```

**Comment by lslebodn** [comment]
Proposed output looks good to me.

Thank you very much.

**Comment by kparal** [comment]
> Honestly, I don't know why the full log is not accessible.

Our results can currently store just a single hyperlink, which we use to link to the main task artifact (`output.log` in your case). We haven't added navigation yet that would allow people to reach other artifacts or the execution log. Adding the detailed dependency evaluation into `output.log` as you propose above is the best solution for now.

**Comment by hroncok** [comment]
I've just pushed a significant load of changes to the devel branch. Will check if it works on the staging Taskotron and merge to master soon.

**Comment by kparal** [comment]
Look at http://taskotron-dev.fedoraproject.org/ instead. We've been using stg to test modularity stuff and standard tests are disabled there for the moment.

**Comment by hroncok** [comment]
Doing that (said staging, meant dev, edited). @kparal Does this run on scratch builds as well or do i need to wait until someone screw up?

**Comment by hroncok** [comment]
So far no FAILED task :(

**Comment by kparal** [comment]
No, sorry, we don't run on scratch builds atm.

**Comment by hroncok** [comment]
Here we go:

https://taskotron-dev.fedoraproject.org/artifacts/all/99facd22-36a2-11e7-80c1-525400cb0b45/task_output/output.log

```
These RPMs require both Python 2 and Python 3:
python3-qt5-base-5.8.2-2.fc27.i686.rpm
 * Python 2 dependency: python-qt5-rpm-macros
 * Python 3 dependecny: python(abi) = 3.6
python3-qt5-base-5.8.2-2.fc27.armv7hl.rpm
 * Python 2 dependency: python-qt5-rpm-macros
 * Python 3 dependecny: python(abi) = 3.6
python3-qt5-base-5.8.2-2.fc27.x86_64.rpm
 * Python 2 dependency: python-qt5-rpm-macros
 * Python 3 dependecny: python(abi) = 3.6


Read the following document to find more information and a possible cause:
https://python-rpm-porting.readthedocs.io/en/latest/applications.html#are-shebangs-dragging-you-down-to-python-2
Or ask at #fedora-python IRC channel for help.

If you think the result is false or intentional, file a bug against:
https://github.com/fedora-python/task-python-versions/issues
```

**Comment by hroncok** [comment]
Opening https://github.com/fedora-python/task-python-versions/issues/9 for relevant false hit and merging this to master.
